import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import { Modal } from "../../components/Modal/Modal";

import { Location } from "../../components/Location/Location";
import { PostSection } from "../../components/PostSection/PostSection";
import { SearchBanner } from "../../components/SearchBanner/SearchBanner";
import styles from "../../styles/Page.module.scss";
import { useState } from "react";
import { PostForm } from "../../components/forms/PostForm/PostForm";
import { useSession } from "next-auth/react";

interface CategoryListingProps {
  categoryId: string;
}

const CategoryListing: NextPage<CategoryListingProps> = ({
  categoryId,
}: CategoryListingProps) => {
  const [modalOpen, setModalOpen] = useState(false);
  const addPostMutation = trpc.post.addPost.useMutation();

  const { data: session } = useSession();

  const response = trpc.post.getAllForCategoryId.useQuery({
    categoryId: categoryId,
  }).data;

  const handlePostSubmit = (values: {
    title: string;
    content: string;
    tags: string[];
  }) => {
    addPostMutation.mutate({
      content: values.content,
      title: values.title,
      tags: values.tags,
      categoryId: categoryId,
    });
    setModalOpen(false);
  };

  return (
    <>
      <Head>
        <title>{response?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal onClose={() => setModalOpen(false)} isOpen={modalOpen}>
        <PostForm onSubmit={handlePostSubmit} />
      </Modal>
      <SearchBanner />
      <Location
        paths={[{ label: response?.name ?? "", url: `/${categoryId}` }]}
      />
      <div className={styles.maxWidthContainer}>
        {session && (
          <button
            className={styles.transparentButton}
            onClick={() => {
              setModalOpen(true);
            }}
          >
            + Add new post
          </button>
        )}
        <PostSection title={response?.name} posts={response?.posts ?? []} />
      </div>
    </>
  );
};

export default CategoryListing;

export const getServerSideProps: GetServerSideProps<
  CategoryListingProps
> = async (context) => {
  return {
    props: {
      categoryId: `${context.query.categoryId}`,
    },
  };
};
