import { NextPage } from 'next';
import Head from 'next/head';

import { Location } from '../../components/Location/Location';
import { PostSection } from '../../components/PostSection/PostSection';
import { SearchBanner } from '../../components/SearchBanner/SearchBanner';

const mockedPosts = [
  {
    id: 'dsad',
    title: 'Test post 1',
    tags: ['Sofrin', 'Help'],
    lastResponse: 'yesterday',
    likes: 3,
    responses: 3,
    views: 3,
  },
];

const Category: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBanner />
      <Location
        paths={[
          { label: 'Category', url: '/category' },
          { label: 'Post', url: '/category/post' },
        ]}
      />
      <PostSection posts={mockedPosts} />
    </>
  );
};

export default Category;
