import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Page.module.scss";

import { SearchBanner } from "../components/SearchBanner/SearchBanner";
import { PostSection } from "../components/PostSection/PostSection";
import { CategorySection } from "../components/CategorySection/CategorySection";
import { Location } from "../components/Location/Location";
import { trpc } from "../utils/trpc";

const HomePage: NextPage = () => {
  const categories = trpc.category.getAll.useQuery().data ?? [];
  const recents = trpc.post.getRecent.useQuery().data ?? [];

  return (
    <>
      <Head>
        <title>FlashForum Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBanner />
      <Location />
      <div className={styles.maxWidthContainer}>
        <CategorySection
          title="Most popular categories"
          categories={categories}
        />
      </div>
      <div className={styles.maxWidthContainer}>
        <PostSection title="Recent posts" posts={recents} />
      </div>
    </>
  );
};

export default HomePage;
