import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.searchBanner}>
        <input
          className={styles.input}
          id="search"
          name="search"
          type="text"
          placeholder="Search for topics..."
        />
      </section>
    </>
  );
};

export default Home;
